comment_width = 120
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
wrap_comments = true
